apiVersion: v1

kind: Pod

metadata:

  name: my-pod

spec:

  containers:

  - image: ubuntu

    name: my-app
    command:
    - ls
    - "-l"
    - "/tmp/test.txt"

    volumeMounts:

    - mountPath: /cache

      name: cache-volume

  volumes:

    - name: cache-volume

      emptyDir: {}
  restartPolicy: Never
