apiVersion: v1
kind: Pod
metadata:
  name: origin
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
    - name: memcached
      image: memcached
      ports:
        - containerPort: 11211
