apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: pod-secret-env
      image: redis
      command: ["sleep", "3600"]
      env:
        
        - password: origin
                                   
          valueFrom:
            configMapKeyRef:
              name: cm-demo           # The ConfigMap this value comes from.
              key: password
        
          
      volumeMounts:
      - name: config
        mountPath: "/secrets"
        readOnly: true
  volumes:
  
  - name: config
    configMap:
      # Provide the name of the ConfigMap you want to mount.
      name: cm-demo
  containers:
  - name: pod-secret-file
    image: redis
    valueFrom:
            configMapKeyRef:
              name: cm-demo           # The ConfigMap this value comes from.
              key: name
    volumeMounts:
    - name: config1
      mountPath: "/secrets"
      readOnly: true
  volumes:
  - name: config1
    configMap:
      name: cm-demo
